//Register user
# POST http://localhost:5000/customer/register
# Content-Type: application/json
# POST https://ec2-13-232-220-12.projects.wecreateproblems.com/proxy/5000/customer/register
//Login user
POST http://localhost:5000/customer/login
Content-Type: application/json



//Registeration Json
{
    "name": "Basu",
    "email": "example@example.com",
    "username": "BASU4100",
    "password": "basu1234",
    "role": "USER"
}

# {
#     "name": "Vivek",
#     "email": "example@example.com",
#     "username": "VIVEK4100",
#     "password": "pass123456",
#     "role": "ADMIN"
# }

#Duplicate to get Error
# {
#     "name": "Vivek Basu",
#     "email": "example1@example.com",
#     "username": "VIVEK4100",
#     "password": "pass12356",
#     "role": "ADMIN"
# }

// Login Json
//User
# {
#     "username": "BASU4100",
#     "password": "pass123"
# }

//Admin
{
    "username": "VIVEK4100",
    "password": "pass123456"
}