###
//Register user
POST http://localhost:5000/customer/register
Content-Type: application/json

//Registeration Json
{
    "name": "Basu",
    "email": "example@example.com",
    "username": "BASU4100",
    "password": "basu1234",
    "role": "USER"
}

# {
#     "name": "Rimi",
#     "email": "rimi@example.com",
#     "username": "rimi4100",
#     "password": "rimi1234",
#     "role": "USER"
# }

# {
#     "name": "Vivek",
#     "email": "example@example.com",
#     "username": "VIVEK4100",
#     "password": "pass123456",
#     "role": "ADMIN"
# }

#Duplicate to get Error
# {
#     "name": "Vivek Basu",
#     "email": "example1@example.com",
#     "username": "VIVEK4100",
#     "password": "pass12356",
#     "role": "ADMIN"
# }

###
//Login user
POST http://localhost:5000/customer/login
Content-Type: application/json

// Login Json
//User
# {
#     "username": "BASU4100",
#     "password": "basu1234"
# }

//Admin
# {
#     "username": "VIVEK4100",
#     "password": "vivek1234"
# }