# POST http://localhost:5000/transactions
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzYxMTA5NzEwLCJleHAiOjE3NjExOTYxMTB9.cgQ3P9BwXaxN5ZER-fhv0cb9NmZw6P6z4bjR4kDqS8GLARdLjjztAP0ONMOlOshQgydL6Xb_o3W0wBG63NwzQQ

# {
#     "amount": 2000,
#     "transactionType": "credit",
#     "transactionDate": "2025-10-20",
#     "accounts": {
#         "accountId": 6
#     }
# }

###Get all transactions
# GET http://localhost:5000/transactions
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjA5NzkyNjgsImV4cCI6MTc2MTA2NTY2OH0.kr7Oz6aJsZa2u4O-VDEbqYR2ksimk2fS5ig96WUP50qmm-wbExYehJ05UdIuVEqgBrrCyknpq0ISe-3_0HKn-g

# ###Get by id
# GET http://localhost:5000/transactions/6
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCQVNVNDEwMCIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzYxMTA5NzEwLCJleHAiOjE3NjExOTYxMTB9.cgQ3P9BwXaxN5ZER-fhv0cb9NmZw6P6z4bjR4kDqS8GLARdLjjztAP0ONMOlOshQgydL6Xb_o3W0wBG63NwzQQ

# ###Updated
# PUT http://localhost:5000/transactions/1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjA5NzkyNjgsImV4cCI6MTc2MTA2NTY2OH0.kr7Oz6aJsZa2u4O-VDEbqYR2ksimk2fS5ig96WUP50qmm-wbExYehJ05UdIuVEqgBrrCyknpq0ISe-3_0HKn-g

# {
#     "amount": 20000,
#     "transactionType": "credit",
#     "transactionDate": "2025-10-20",
#     "accounts": {
#         "accountId": 7
#     }
# }

# ###
DELETE http://localhost:5000/transactions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWSVZFSzQxMDAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjA5NzkyNjgsImV4cCI6MTc2MTA2NTY2OH0.kr7Oz6aJsZa2u4O-VDEbqYR2ksimk2fS5ig96WUP50qmm-wbExYehJ05UdIuVEqgBrrCyknpq0ISe-3_0HKn-g